spring:
  cloud:
    gateway:
      routes:
        - id: books-service
          uri: http://localhost:8081
          predicates:
            - Path=//librarry/**
        - id: users-service
          uri: http://localhost:8082
          predicates:
            - Path=/users/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
